'use client';
import { useState } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
const links = [{ label: 'Overview', href: '/' }, { label: 'Integrations', href: '/#integrations' }, { label: 'Guide', href: '/docs' }];
export default function NavHeader() {
  const [open, setOpen] = useState(false);
  const pathname = usePathname();
  return <header className="fixed inset-x-0 top-0 z-50 bg-surface/95 backdrop-blur border-b border-outline-variant/30 text-on-surface"><div className="h-16 max-w-7xl mx-auto px-6 md:px-12 flex items-center justify-between gap-4"><Link href="/" onClick={() => setOpen(false)} className="flex items-center gap-2 font-semibold text-lg"><span className="material-symbols-outlined bg-primary text-on-primary rounded-lg p-1.5 text-xl" aria-hidden="true">hub</span>AgentForge</Link><nav aria-label="Main navigation" className="hidden md:flex gap-6 text-sm">{links.map(link => <Link key={link.href} href={link.href} aria-current={pathname === link.href ? 'page' : undefined} className={pathname === link.href ? 'text-primary font-semibold' : 'text-on-surface-variant hover:text-primary'}>{link.label}</Link>)}</nav><div className="flex gap-2 items-center"><Link className="bg-primary text-on-primary rounded-lg px-4 py-2 text-sm font-semibold" href="/admin/login">Admin login</Link><button className="md:hidden p-2" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(value => !value)}><span className="material-symbols-outlined" aria-hidden="true">{open ? 'close' : 'menu'}</span></button></div></div>{open && <nav id="mobile-navigation" aria-label="Mobile navigation" className="md:hidden border-t border-outline-variant/20 px-6 py-3 flex flex-col gap-1">{links.map(link => <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className="rounded-lg px-3 py-3 text-sm hover:bg-surface-container-low">{link.label}</Link>)}</nav>}</header>;
}
