import Link from 'next/link';
const features = [
  { icon: 'description', title: 'Answers from your policies', text: 'Upload PDF or text documents so customers can ask about delivery, returns, and company policies.' },
  { icon: 'local_shipping', title: 'Personal order updates', text: 'Check the signed-in customer’s order status and tracking details from the company database.' },
  { icon: 'mail', title: 'Email when requested', text: 'Send an order update to the email address the customer supplies.' },
  { icon: 'support_agent', title: 'A manager when needed', text: 'Route refund requests for review and show the customer the manager’s decision.' },
];
export default function Home() {
  return <div className="bg-surface text-on-surface">
    <section className="max-w-7xl mx-auto px-6 md:px-12 py-20 md:py-28 grid lg:grid-cols-2 gap-12 items-center">
      <div><span className="inline-block rounded-full bg-primary/10 text-primary px-3 py-1 text-xs font-semibold">Customer support, on your website</span><h1 className="text-5xl md:text-7xl font-semibold tracking-tight leading-[1.08] mt-6">Your company.<br /><span className="text-primary">Your assistant.</span></h1><p className="text-lg text-on-surface-variant mt-6 max-w-lg leading-relaxed">Help customers understand your policies, check their orders, and reach your team—all from your own website.</p><div className="flex flex-wrap gap-3 mt-8"><Link href="/admin/login" className="bg-primary text-on-primary rounded-lg px-5 py-3 font-semibold">Company admin</Link><Link href="/docs" className="border border-outline-variant rounded-lg px-5 py-3 font-semibold">Integration guide</Link></div></div>
      <div className="rounded-3xl border border-outline-variant/30 bg-surface-container-lowest shadow-lg p-6 md:p-8"><div className="flex items-center gap-3 border-b border-outline-variant/20 pb-5"><span className="bg-primary/10 text-primary rounded-xl p-3 material-symbols-outlined">chat_bubble</span><div><h2 className="font-semibold">Support that stays with your customer</h2><p className="text-sm text-on-surface-variant mt-1">Widget or your own API interface</p></div></div><div className="space-y-5 mt-6">{features.map(feature => <div className="flex gap-4" key={feature.title}><span className="material-symbols-outlined text-primary mt-1">{feature.icon}</span><div><h3 className="font-semibold">{feature.title}</h3><p className="text-sm text-on-surface-variant mt-1 leading-relaxed">{feature.text}</p></div></div>)}</div></div>
    </section>
    <section id="integrations" className="scroll-mt-24 bg-surface-container-low/60 border-y border-outline-variant/20"><div className="max-w-7xl mx-auto px-6 md:px-12 py-16"><h2 className="text-3xl font-semibold tracking-tight">Two ways to meet your customers</h2><p className="text-on-surface-variant mt-3">Prepared fictional companies show both integration styles.</p><div className="grid md:grid-cols-2 gap-6 mt-8"><article className="bg-surface-container-lowest rounded-2xl p-7 border border-outline-variant/30"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Embedded chat bubble</span><h3 className="text-2xl font-semibold mt-3">Walkwave</h3><p className="text-on-surface-variant mt-3 leading-relaxed">A Sri Lankan shoe storefront. Customers open support in the bottom-right corner and continue shopping on the same page.</p><Link className="inline-flex items-center gap-2 text-primary font-semibold mt-6" href="/walkwave">Open Walkwave <span aria-hidden="true">→</span></Link></article><article className="bg-surface-container-lowest rounded-2xl p-7 border border-outline-variant/30"><span className="text-xs font-semibold uppercase tracking-wider text-primary">Enterprise API</span><h3 className="text-2xl font-semibold mt-3">Nova Electronics</h3><p className="text-on-surface-variant mt-3 leading-relaxed">A technology storefront with its own support interface. Its server connects to AgentForge through the chat API.</p><Link className="inline-flex items-center gap-2 text-primary font-semibold mt-6" href="/nova">Open Nova <span aria-hidden="true">→</span></Link></article></div></div></section>
    <section id="manage" className="scroll-mt-24 max-w-7xl mx-auto px-6 md:px-12 py-16"><h2 className="text-3xl font-semibold tracking-tight">A simple workspace for your team</h2><div className="grid md:grid-cols-3 gap-8 mt-8">{[['01', 'Add company knowledge', 'Upload policies and product information in the Knowledge Base.'], ['02', 'Manage customer access', 'Use the prepared customer accounts to demonstrate personal order lookup.'], ['03', 'Review customer requests', 'Check escalations, record a decision, and monitor agent activity.']].map(([step,title,text]) => <div key={step}><span className="text-primary text-sm font-semibold">{step}</span><h3 className="font-semibold text-lg mt-3">{title}</h3><p className="text-sm text-on-surface-variant mt-2 leading-relaxed">{text}</p></div>)}</div></section>
  </div>;
}
